# Generated by Django 3.2.7 on 2021-09-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('eventid', models.IntegerField(default=0)),
                ('imgdata', models.CharField(max_length=45)),
                ('postdata', models.CharField(max_length=1000, null=True)),
                ('posttime', models.CharField(max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.IntegerField(default=0)),
                ('userid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('reg_no', models.CharField(max_length=11)),
                ('profilepic', models.CharField(max_length=45, null=True)),
                ('lflag', models.IntegerField(default=0)),
                ('password_reset', models.CharField(default=0, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=51, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
