# Generated by Django 3.2.7 on 2021-09-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0002_alter_userdetails_password_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventpic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imgdata',
            field=models.CharField(max_length=50),
        ),
    ]
