# Generated by Django 3.2.7 on 2021-10-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0003_auto_20210925_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='androidtoken',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='userid',
            name='webtoken',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
