# Generated by Django 3.2.7 on 2021-10-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0004_auto_20211005_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='resetpwdtoken',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
