# Generated by Django 3.2.7 on 2021-10-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0005_userdetails_resetpwdtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventupdate',
            name='imgdata',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventupdate',
            name='postedon',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='eventupdate',
            name='updateid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventupdate',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventupdate',
            name='viewedby_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventupdate',
            name='visible_status',
            field=models.IntegerField(default=0),
        ),
    ]
