# Generated by Django 3.2.7 on 2021-10-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0006_auto_20211015_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventupdate',
            name='eventmessage',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userid',
            name='usertype',
            field=models.IntegerField(default=4),
        ),
    ]
