# Generated by Django 3.2.7 on 2021-10-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0007_auto_20211016_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='altemail',
            field=models.CharField(max_length=51, null=True, unique=True),
        ),
    ]
