# Generated by Django 3.2.7 on 2021-10-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0008_userdetails_altemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='participants_per_team',
            field=models.IntegerField(default=1),
        ),
    ]
