# Generated by Django 3.2.7 on 2021-10-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0009_events_participants_per_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventdate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='posterpic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
