# Generated by Django 3.2.7 on 2021-11-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0011_eventqueries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventqueries',
            name='respondedby',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eventqueries',
            name='response',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
