# Generated by Django 3.2.7 on 2021-11-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0012_auto_20211112_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventqueries',
            name='response',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
