# Generated by Django 3.2.7 on 2021-11-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0013_alter_eventqueries_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventqueries',
            name='respondedby',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
