# Generated by Django 3.2.7 on 2021-11-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0014_alter_eventqueries_respondedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventqueries',
            name='response',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
