# Generated by Django 3.2.7 on 2021-11-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0015_alter_eventqueries_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventqueries',
            name='response',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
