# Generated by Django 3.2.7 on 2021-11-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0017_alter_eventqueries_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventupdate',
            name='viewedby_status',
        ),
        migrations.RemoveField(
            model_name='eventupdate',
            name='visible_status',
        ),
    ]
