# Generated by Django 3.2.7 on 2021-11-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mectculturals', '0018_auto_20211114_0903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='eventupdate',
            name='updateid',
        ),
    ]
